### ISSUE TITLE
TFS-Sync

### ISSUE THREAD

**Issue by ThiloL** [scriptrunner/ActionPacks#3]
Der TFS-Sync kann zwar initial einen Sync vom TFS "runter" machen, aber geänderte (bereits vorhandene) dateien werden nicht aktualisiert.

**Comment by AchimWieser** [comment]
Hallo Thilo,

vielen Dank für den Hinweis.
Nun wird im Skript die GetOption Overwrite verwendet, um bestehende Dateien zu überschreiben.
Mit dem Switch CleanSync kann man seinen lokalen Workspace vor einem "get" löschen. 

Viele Grüße
Achim Wieser
vom ScriptRunner Team

closed by 2d66dc5
