### ISSUE TITLE
VMs not sorted by Name

### ISSUE THREAD

**Issue by PSTobiasMueller** [scriptrunner/ActionPacks#8]
Hello Scriptrunner Team,

don't know if this is the right place... :-) 

One point that was really inconvenient for us where with the VMware Action Packs. The Queries are not sorted. For example the Querys QUY_Get-VMHVVirtualMachineIDs.ps1 or QUY_Get-VMHVVirtualMachines.ps1. Sure you have Intellisense in the textbox, but some user tend to scroll through the list to get the right VM.

Thats why we added an ` | Sort-Object -Property Name | ` after the `Select-Object ..... `  to the two queries mentioned above for example.
Does it make sense to add that for all customers?

Greetings
Tobias

**Comment by AchimWieser** [comment]
Hi Tobias,

I think, this would be helpful for all customers.
You are very welcome to add a pull request for the mentioned changes.

Greetings,
Achim

**Comment by HaraldPfirmann** [comment]
Hi Tobias,

the queries are now sorted.

Best regards 
Harald
