### ISSUE TITLE
Get-DMSSIMGeneric Query Issue

### ISSUE THREAD

**Issue by sstover-544** [scriptrunner/ActionPacks#9]
I get an error when I run get-DMSSIMGeneric query. Error is about $connectionName variable being empty. The script uses OpenSQLConnection which has a default connection name of SRConnection, so simply using CloseConnection without any additonal arguments fixed the issue since that function also has a default connection name of SRConnection. 

finally{
    CloseConnection -ConnectionName $ConnectionName
}
changed to:

finally{
    CloseConnection 
}

**Comment by HaraldPfirmann** [comment]
Many thanks for your reply.
The problem has been fixed
